name: issue-checklist

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      if: 
        ${{ 
          !contains(
            fromJson('[
              "aleksey-hoffman",
              "photoancestry",
              "andyundso",
              "theoob",
              "julienripet",
              "exploitacious",
              "HarkTu"
            ]'), 
            github.actor
          ) 
        }}
      with:
        message: Consider supporting the developer to increase priority of all your issues and get other rewards
          <br>https://github.com/aleksey-hoffman/sigma-file-manager/wiki/Supporter-rewards
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
